config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :cities

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  country    :string           not null
#  photo      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class City <ApplicationRecord
    validates :name, :country, presence: true
    validates :name, uniqueness: {scope: [:country]}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  roles                  :string           default("user")
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_user
  
  
  private
  
  def get_user
      @user = current_user
      @is_logged_in = user_singed_in?
      @is_user = @is_logged_in && @user.role == 'user'
      @is_user = @is_logged_in && @user.role == 'admin'
  end
  
  def auth_admin
      redirect_to root_url if !@is_admin
      
  end
  
  def auth_user
      redirect_to root_url if !@is_user
end
  
end

app/controllers/cities_controller.rb
class CitiesController <ApplicationController
    before_action :auth_admin #before any action below run this function
    
    
    def index
         @cities = City.all

    end

    def new
        @city = City.new
    end

    def create
        @city = City.new(params[:city].permit(:name, :country, :photo))
            if @city.save
                redirect_to cities_path
            else
                render 'new'
            end
        
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/index.html.erb
Cities
<div>
    <%= link to 'New City', new_city_path %>
</div>
<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Country</th>
            <th>Photo</th>
                
            </th>
        </tr>
    </thead>
    <tbody>
        <% @cities.each do |c| %>
            <tr>
                <td><%= c.id %></tr>
                <td><%= c.name %></tr>
                <td><%= c.country %></tr>
                <td><%= c.photo %></tr>
    <% end %>
        
    </tbody>
</table>

app/views/cities/new.html.erb
<%= form_with(model: @city, local: true) do |form| %>
<%= render 'errors', object: @city %>
      
      <div class="form-group">

        <%= form.label :name %>

        <%= form.text_field :name, id: :city_name, class: 'form-control' %>

      </div>



      <div class="form-group">

        <%= form.label :country %>

        <%= form.text_field :country, id: :city_country, class: 'form-control' %>

      </div>



      <div class="form-group">

        <%= form.label :photo %>

        <%= form.text_field :photo, id: :city_photo, class: 'form-control' %>

      </div>



      <div class="form-group">

        <%= form.submit class: 'btn btn-outline-primary' %>

      </div>

    <% end %>      

app/views/home/index_html.erb
my awesome homepage

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carnival</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>